version: '3.0'

services:
  rasa:
    image: samtecspg/rasa-tutorials:tensorflow
    ports:
    - 5000:5000
    volumes:
    - ./models:/app/models
  node-red:
    image: samtecspg/node-red-tutorials
    user: '1000'
    ports:
    - 1880:1880
    volumes:
      - ./data:/data